### ISSUE TITLE
Boost program options not parsed?

### ISSUE THREAD

**Issue by kenaycock** [kgram007/Eulerian-Motion-Magnification#3] opened 2018-11-12 22:43 UTC
Running the test case produces the following error:
```
./bin/Eulerian_Motion_Magnification test/test_baby.param
Error: Unable to open input video file: 
```
It seems that the Boost program options are not read from the .param file. Any ideas why this might be? 

I am running on Linux, Boost 1.54.0.1

**Comment by kgram007** [comment] 2018-11-13 03:46
I tested the code on Windows machine with Boost 1.61.0 and It works for me. Not sure if the issue you're seeing is caused by the Boost version. Also, I am yet to test my code on a Linux machine.

**Comment by kgram007** [comment] 2020-09-22 01:40
Tested on Linux machine with Boost version: 1.65.1 and it works. Closing this issue, if needed can be reopened later.

**Closed as completed by kgram007** 2020-09-22 01:40 UTC
